ci: Improve handling of build log copying

diff --git a/.github/actions/ci-build-step/action.yml b/.github/actions/ci-build-step/action.yml
--- a/.github/actions/ci-build-step/action.yml
+++ b/.github/actions/ci-build-step/action.yml
@@ -72,9 +72,13 @@ runs:
         find /nix/var/log/nix/drvs -type f -printf '%P\n' |
           while read log_src; do
             log_dst="${log_src//\//}"
-            cp -v /nix/var/log/nix/drvs/"$log_src" .build/logs/"$log_dst" ||:
+            printf '%s\n' "$log_dst"
+            cp -v /nix/var/log/nix/drvs/"$log_src" .build/logs/"$log_dst" || touch .build/logs_fail
           done
         echo "::endgroup::"
+        if [ -f .build/logs_fail ]; then
+          echo "Warning: Some log files could not be copied" 1>&2
+        fi
         exit $build_result
     - name: Upload build logs
       if: ${{ always() }}
